/**
 * Team entity factory for the Whoville-Client Workforce module.
 *
 * Generates entities with `e2e-test-` prefixed names so the live-mode
 * entity sweeper (e2e/utils/test-data-cleanup.ts) can identify orphan
 * test entities for removal per AAP §0.4.4.
 *
 * Uses `@faker-js/faker` (version pinned per AAP §0.6.1: `^9.0.0`).
 *
 * Foundational layer — imports only `@faker-js/faker`. Pure data
 * generation with no I/O, no Node.js built-ins, no other factory
 * dependencies (no sibling-factory imports per AAP §0.10.1). Each call
 * produces an independent, parallel-safe instance suitable for use by
 * Playwright workers running concurrently.
 *
 * ## Cleanup contract (AAP §0.4.4 — Live-mode database hygiene)
 *
 * The live-mode sweeper identifies deletion candidates by inspecting the
 * `name` field. The field begins with the configured `e2e-test-` prefix
 * (default), and a randomized 8-character alphanumeric suffix guarantees
 * uniqueness across parallel workers per AAP §0.10.1.
 *
 * ## Migration-proof shape (AAP §0.10.1)
 *
 * All exported types use only primitive TypeScript types and
 * `ReadonlyArray<string>` for collections. No Angular-specific types, no
 * Whoville-Client class references, no runtime decorators.
 *
 * ## Determinism (AAP §0.4.4)
 *
 * All `faker.date.*` calls use a seed-deterministic `refDate` produced by
 * `deterministicDateAnchor()`. See QA Issue #3 for the wall-clock drift
 * defect this avoids.
 *
 * @see AAP §0.5.1.12 — file mandate (Factories, Mocks, and Test Utilities).
 * @see AAP §0.4.4 — Test Data and Fixtures Design.
 * @see AAP §0.10.1 — User-specified directives.
 * @see e2e/pages/workforce/team-list.page.ts, team-detail.page.ts,
 *      team-form.page.ts — POM consumers.
 * @see e2e/mocks/handlers/workforce.handler.ts — mock handler consumer.
 * @see e2e/fixtures/api-responses/workforce/teams-list.json,
 *      team-detail.json — fixture shape references.
 */

// ---------------------------------------------------------------------------
// Imports — strictly limited to `@faker-js/faker`.
// ---------------------------------------------------------------------------

import { faker } from '@faker-js/faker';

// ---------------------------------------------------------------------------
// Public type definitions
// ---------------------------------------------------------------------------

/**
 * Lifecycle status of a team.
 *
 * Closed union for compile-time safety.
 *
 * - `'active'`     — Currently operational; appears in default list views.
 * - `'archived'`   — Soft-deleted; still queryable for audit but excluded
 *                    from default list views.
 * - `'dissolved'`  — Permanently disbanded; retained only for audit
 *                    history. Members are reassigned elsewhere.
 */
export type TeamStatus = 'active' | 'archived' | 'dissolved';

/**
 * Team entity. Represents a workforce organisational unit in the
 * Whoville-Client Workforce module.
 *
 * Migration-proof shape: primitive types only.
 *
 * Field stability:
 *   - `id` and `name` are stable identifiers; `name` is the cleanup
 *     marker. `name` carries the `e2e-test-` prefix and a unique suffix.
 *   - `slug` is a URL-safe lowercase form of the name suitable for use
 *     in route paths; it carries the `e2e-test-` prefix to remain
 *     visually identifiable.
 *   - Cross-factory relationships (`leadUserId`, `parentTeamId`) are
 *     stored as UUID strings — no nested objects — to keep this factory
 *     at the foundational layer.
 *   - `headcount` is an integer (count of members at snapshot time).
 *   - Geographic / cost-center metadata is included for realistic
 *     fixture data; tests that don't care about these fields ignore them.
 *
 * @see AAP §0.5.1.13 — `e2e/fixtures/api-responses/workforce/teams-list.json`,
 *      `team-detail.json` mirror this shape.
 */
export interface Team {
  /** UUID identifier (RFC 4122 v4). */
  readonly id: string;
  /**
   * `e2e-test-` prefixed display name for live-mode cleanup eligibility.
   *
   * Format: `e2e-test-<dept>-<8-char-suffix>` (e.g.,
   * `'e2e-test-engineering-x7y8a3bc'`).
   */
  readonly name: string;
  /**
   * `e2e-test-` prefixed URL-safe slug derived from the name.
   *
   * Format: `e2e-test-<dept>-<8-char-suffix>` (lowercase, hyphenated).
   * Suitable for use in route params (`/workforce/teams/:slug`).
   */
  readonly slug: string;
  /**
   * Optional human-readable description of the team's mission /
   * responsibilities. Realistic prose generated by faker.
   */
  readonly description?: string;
  /** Current lifecycle status (closed union — see {@link TeamStatus}). */
  readonly status: TeamStatus;
  /**
   * UUID of the user serving as team lead. `null` for teams without an
   * assigned lead (e.g., newly-created teams pending lead assignment).
   * Cross-factory relationship stored as a UUID string.
   */
  readonly leadUserId: string | null;
  /**
   * UUID of the parent team in the organisational hierarchy. `null` for
   * top-level teams.
   */
  readonly parentTeamId: string | null;
  /**
   * Snapshot count of team members at last update. Integer ≥ 0. The
   * snapshot may briefly drift from reality during transfer windows;
   * tests that assert on exact counts should refresh the entity first.
   */
  readonly headcount: number;
  /**
   * Geographic location (city / metro region) — free-form string drawn
   * from faker's location provider. Used for filtering in list views.
   */
  readonly location: string;
  /**
   * Cost center accounting code. Format: `CC-NNNNN` (e.g., `CC-12345`).
   * Used by reporting export workflows.
   */
  readonly costCenter: string;
  /** ISO 8601 timestamp of creation. */
  readonly createdAt: string;
  /** ISO 8601 timestamp of last update. Optional — absent for never-modified rows. */
  readonly updatedAt?: string;
}

// ---------------------------------------------------------------------------
// Internal constants — file-local; not exported.
// ---------------------------------------------------------------------------

/** Common prefix applied to every entity name / slug for cleanup eligibility. */
const E2E_TEST_PREFIX = 'e2e-test-';

/** Length of the random alphanumeric uniqueness suffix. */
const UNIQUE_SUFFIX_LENGTH = 8;

/**
 * Canonical department slugs for team naming. Drawn from typical
 * enterprise organisational structure; the `<dept>` token in the
 * `name` / `slug` field is selected from this list.
 */
const TEAM_DEPARTMENT_SLUGS = [
  'engineering',
  'product',
  'design',
  'operations',
  'finance',
  'hr',
  'sales',
  'marketing',
  'support',
  'compliance',
] as const;

/**
 * Weighted distribution for `TeamStatus`. `'active'` is over-represented
 * to bias towards production reality (most teams are operational).
 */
const TEAM_STATUS_DISTRIBUTION: ReadonlyArray<TeamStatus> = [
  'active',
  'active',
  'active',
  'active',
  'archived',
  'dissolved',
];

/** Probability (0–1) that a generated team has a description. */
const PROBABILITY_HAS_DESCRIPTION = 0.85;

/** Probability (0–1) that a generated team has an assigned lead. */
const PROBABILITY_HAS_LEAD = 0.9;

/** Probability (0–1) that a generated team has a parent team. */
const PROBABILITY_HAS_PARENT = 0.4;

/** Minimum headcount for a generated team. */
const MIN_HEADCOUNT = 0;

/** Maximum headcount for a generated team. Realistic upper bound for an enterprise org unit. */
const MAX_HEADCOUNT = 250;

/** Minimum word count for the description sentence. */
const MIN_DESCRIPTION_WORDS = 5;

/** Maximum word count for the description sentence. */
const MAX_DESCRIPTION_WORDS = 12;

/** Lookback window (days) for `createdAt` timestamps. */
const RECENT_DAYS_CREATED = 1095;

/** Lookback window (days) for `updatedAt` timestamps. */
const RECENT_DAYS_UPDATED = 90;

// ---------------------------------------------------------------------------
// Determinism anchor (per AAP §0.4.4)
// ---------------------------------------------------------------------------

/** Lower bound of the deterministic date anchor: 2020-01-01T00:00:00.000Z. */
const ANCHOR_MIN_EPOCH_MS = Date.UTC(2020, 0, 1);

/** Upper bound of the deterministic date anchor: 2030-12-31T00:00:00.000Z. */
const ANCHOR_MAX_EPOCH_MS = Date.UTC(2030, 11, 31);

/**
 * Generate a seed-deterministic `Date` anchor without consulting the
 * wall-clock. See e2e/factories/role-grant.factory.ts for the full
 * rationale — short version: faker's `date.*` API defaults `refDate` to
 * `new Date()`, breaking byte-identical reproducibility under same-seed
 * invocations. QA Issue #3 documented this defect at ~10% rate.
 */
function deterministicDateAnchor(): Date {
  return new Date(faker.number.int({ min: ANCHOR_MIN_EPOCH_MS, max: ANCHOR_MAX_EPOCH_MS }));
}

// ---------------------------------------------------------------------------
// Public factory
// ---------------------------------------------------------------------------

/**
 * Generate a {@link Team} instance with sensible defaults and optional
 * overrides.
 *
 * Each invocation produces an independent, parallel-safe instance:
 *   - `id` is a fresh RFC 4122 v4 UUID.
 *   - `name` and `slug` carry the `e2e-test-` prefix and an 8-character
 *     random suffix. `slug` is the lowercase, hyphenated URL-safe form
 *     of `name`.
 *   - `status` is weighted so ~67 % of teams are `'active'`.
 *   - `headcount` is a random integer in [0, 250].
 *   - `leadUserId` and `parentTeamId` are fresh UUIDs (with configured
 *     null-probability) — these are cross-factory references that the
 *     consumer should override when targeting a specific user/team.
 *
 * @example Default team:
 * ```ts
 * const t = teamFactory();
 * // -> { id: '...', name: 'e2e-test-engineering-a3b8x2pq', ... }
 * ```
 *
 * @example Targeted override (specific lead and parent):
 * ```ts
 * const child = teamFactory({
 *   leadUserId: knownUser.id,
 *   parentTeamId: parentTeam.id,
 *   status: 'active',
 * });
 * ```
 *
 * @example Archived team for negative-path tests:
 * ```ts
 * const archived = teamFactory({ status: 'archived' });
 * ```
 *
 * @param overrides Partial fields to override on the generated instance.
 *                  Defaults to an empty object.
 * @returns A fully-populated {@link Team} object.
 */
export function teamFactory(overrides: Partial<Team> = {}): Team {
  // Department slug drives both `name` and `slug` so test failures
  // referencing a team can be traced back to the department quickly.
  const department = faker.helpers.arrayElement(TEAM_DEPARTMENT_SLUGS);

  // 8-character lowercase alphanumeric suffix guarantees uniqueness
  // across parallel test workers.
  const uniqueSuffix = faker.string.alphanumeric({
    length: UNIQUE_SUFFIX_LENGTH,
    casing: 'lower',
  });
  const slug = `${E2E_TEST_PREFIX}${department}-${uniqueSuffix}`;

  // `name` matches `slug` because slug is the URL-safe form of name.
  // For teams whose names need different formatting (e.g., capitalised),
  // tests override `name` directly.
  const name = slug;

  // Description: short lorem-ipsum sentence — present in ~85% of teams,
  // matching production reality where a small fraction of teams omit
  // descriptions (typically newly-created teams).
  const hasDescription = faker.datatype.boolean({ probability: PROBABILITY_HAS_DESCRIPTION });
  const description = hasDescription
    ? faker.lorem.sentence({
        min: MIN_DESCRIPTION_WORDS,
        max: MAX_DESCRIPTION_WORDS,
      })
    : undefined;

  // Weighted random status — `'active'` is over-represented to match
  // production-realistic distributions.
  const status: TeamStatus = faker.helpers.arrayElement<TeamStatus>(TEAM_STATUS_DISTRIBUTION);

  // Cross-factory relationships stored as UUID strings (no nested
  // objects per the foundational-layer constraint). Tests that need to
  // reference a specific user/team override these fields.
  const hasLead = faker.datatype.boolean({ probability: PROBABILITY_HAS_LEAD });
  const leadUserId = hasLead ? faker.string.uuid() : null;

  const hasParent = faker.datatype.boolean({ probability: PROBABILITY_HAS_PARENT });
  const parentTeamId = hasParent ? faker.string.uuid() : null;

  // Random headcount in [0, 250]. The lower bound of 0 is realistic for
  // newly-created teams; the upper bound matches enterprise org-unit
  // norms (larger units are typically split into sub-teams).
  const headcount = faker.number.int({ min: MIN_HEADCOUNT, max: MAX_HEADCOUNT });

  // Realistic-looking location and cost-center for fixture data. Tests
  // that filter by location override directly.
  const location = faker.location.city();
  const costCenter = `CC-${faker.string.numeric(5)}`;

  // Determinism anchor — see `deterministicDateAnchor()` for rationale.
  const dateAnchor = deterministicDateAnchor();

  const createdAt = faker.date
    .recent({ days: RECENT_DAYS_CREATED, refDate: dateAnchor })
    .toISOString();
  const updatedAt = faker.date
    .recent({ days: RECENT_DAYS_UPDATED, refDate: dateAnchor })
    .toISOString();

  return {
    id: faker.string.uuid(),
    name,
    slug,
    description,
    status,
    leadUserId,
    parentTeamId,
    headcount,
    location,
    costCenter,
    createdAt,
    updatedAt,
    ...overrides,
  };
}
